# Generated by Django 4.2.3 on 2023-07-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contant',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='student',
            name='classname',
            field=models.IntegerField(default=1),
        ),
    ]
